name: developerFeedback

services:
  mongo:
    image: mongo
    container_name: mongo-container
    networks:
      - my-app
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build:
      context: ./backend
      dockerfile: dockerFile
    restart: unless-stopped
    env_file: ./backend/.env
    command: npm run dev
    networks:
      - my-app
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerFile
    restart: unless-stopped
    env_file: ./frontend/.env
    command: npm run dev -- --host
    networks:
      - my-app
    ports:
      - "5173:5173"
    depends_on:
      - api

networks:
  my-app:
    driver: bridge

volumes:
  mongo-data:
